/*
 * BrowserWasmBackend module-loading smoke (dynamic-loading-all-platforms todo 8).
 *
 * Emscripten-only executable, booted headlessly by scripts/smoke_web.mjs
 * (same --variant CLI as todo 5). Exercises the REAL loader path —
 * load_portable_wasm_plugin_binary -> BrowserWasmBackend::instantiate ->
 * query_portable_wasm_plugin (descriptor decode) -> activate (host imports
 * bound, configure, start) — then invokes the guest's annotated export
 * through the backend and asserts the returned value, plus the invalid-bytes
 * failure path (BackendFailure issue, no crash).
 *
 * Todo 10 extension: the annotated exports are invoked through the GENERIC
 * DESCRIPTOR-DRIVEN dispatcher (browser_wasm_invoke_typed_export). The guest's
 * annotation table is read live from the instance memory (the extraction
 * tool's resolution algorithm, in miniature), validated, and its decoded
 * marshaling descriptors drive the calls — tag -> extract -> manifest ->
 * dispatcher end to end, no per-module glue.
 *
 * The embedded guest bytes are staged onto the emscripten MEMFS so the
 * production file-based loader runs verbatim; no loader code changed.
 *
 * Web builds compile without exceptions and without a test framework
 * (BUILD_TESTING is OFF on emscripten), so failures print a FATAL marker and
 * return nonzero; the node runner treats a nonzero exit and the missing
 * success marker as a failed smoke.
 */
#include "browser_wasm_backend.hpp"

#include "modules/module_manifest.hpp"
#include "plugins/wasm_runtime.hpp"

#include <mobagen/module/module_abi.h>
#include <mobagen/plugin/wasm_abi.h>

#include <array>
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <filesystem>
#include <fstream>
#include <span>
#include <string>
#include <vector>

/* Generated by the guest-build step: mobagen_smoke_guest_wasm.h */
#include "mobagen_smoke_guest_wasm.h"

namespace {

  int failures = 0;

  void check(bool ok, const char* what) {
    if (ok) {
      std::printf("[browser-smoke] PASS: %s\n", what);
    } else {
      std::printf("[browser-smoke] FATAL: %s\n", what);
      ++failures;
    }
  }

  bool stage_file(const std::filesystem::path& path, std::span<const std::byte> bytes) {
    std::error_code error;
    std::filesystem::create_directories(path.parent_path(), error);
    std::ofstream out{path, std::ios::binary | std::ios::trunc};
    if (!out.is_open()) return false;
    out.write(reinterpret_cast<const char*>(bytes.data()), static_cast<std::streamsize>(bytes.size()));
    out.close();
    return out.good();
  }

  std::uint32_t read_guest_u32(const std::byte* memory, std::uint32_t offset) {
    const auto* bytes = reinterpret_cast<const unsigned char*>(memory) + offset;
    return static_cast<std::uint32_t>(bytes[0]) | (static_cast<std::uint32_t>(bytes[1]) << 8U)
           | (static_cast<std::uint32_t>(bytes[2]) << 16U) | (static_cast<std::uint32_t>(bytes[3]) << 24U);
  }

  /*
   * Reads the guest's annotation table from its live linear memory (the
   * mirror view). Mirrors the extraction tool's shape-(b) resolution: the
   * exported global mobagen_module_exports_v1 points (possibly through one
   * indirection) at the table; here the instance memory is already mapped,
   * so the table offset is read directly from the canonical symbol's bytes.
   */
  bool read_annotation_exports(const std::byte* memory, std::size_t memory_bytes, std::vector<mobagen::modules::ModuleManifestExport>& out) {
    if (memory == nullptr || memory_bytes < 16) return false;
    /* The published global's storage sits in the guest's data segment; its
       VALUE is the table offset. Locate it by scanning for the table header
       itself: exactly one MobagenModuleExportTableV1 header with the kind
       magic exists in this guest. */
    for (std::size_t offset = 0; offset + 16U <= memory_bytes; offset += 4U) {
      if (read_guest_u32(memory, static_cast<std::uint32_t>(offset)) != MOBAGEN_MODULE_TABLE_V1) continue;
      const auto abi_version = read_guest_u32(memory, static_cast<std::uint32_t>(offset) + 4);
      const auto entry_count = read_guest_u32(memory, static_cast<std::uint32_t>(offset) + 8);
      if (abi_version != MOBAGEN_MODULE_ABI_VERSION || entry_count == 0 || entry_count > 16) continue;
      const std::size_t first_entry = offset + 16U;
      if (first_entry + entry_count * 16U > memory_bytes) return false;
      for (std::uint32_t index = 0; index < entry_count; ++index) {
        const auto entry = first_entry + index * 16U;
        const auto name_offset = read_guest_u32(memory, static_cast<std::uint32_t>(entry));
        const auto signature_id = read_guest_u32(memory, static_cast<std::uint32_t>(entry) + 8);
        if (name_offset == 0 || name_offset >= memory_bytes) return false;
        std::string name;
        for (std::uint32_t cursor = name_offset; cursor < memory_bytes && name.size() < 128; ++cursor) {
          const auto character = static_cast<char>(memory[cursor]);
          if (character == '\0') break;
          name.push_back(character);
        }
        if (name.empty()) return false;
        mobagen::modules::ModuleExportMarshaling decoded;
        if (!mobagen::modules::decode_module_export_marshaling(signature_id, decoded)) return false;
        out.push_back({std::move(name), signature_id, decoded});
      }
      return !out.empty();
    }
    return false;
  }

}  // namespace

int main() {
  using namespace mobagen::plugins;

  BrowserWasmBackend backend;

  /* 1. Happy path: the production loader pipeline over the embedded guest. */
  const std::span<const std::byte> guest{reinterpret_cast<const std::byte*>(mobagen_smoke_guest_wasm),
                                         mobagen_smoke_guest_wasm_bytes};
  const std::filesystem::path guest_path{"/mobagen-smoke/reference.plugin.wasm"};
  check(stage_file(guest_path, guest), "reference guest staged onto MEMFS");

  auto loaded = load_portable_wasm_plugin_binary(guest_path, backend);
  check(loaded.ok(), "reference guest loaded through BrowserWasmBackend (sync instantiate + descriptor query)");
  if (!loaded.ok() && !loaded.issues.empty()) {
    std::printf("[browser-smoke]   load issue: %s\n", loaded.issues.front().message.c_str());
  }
  if (loaded.ok() && loaded.plugin.has_value()) {
    check(loaded.plugin->provider().id == "mobagen.browser-smoke.default", "queried provider id matches the guest descriptor");

    auto instance = loaded.plugin->take_instance();
    check(instance != nullptr, "loaded instance taken for direct export invocation");

    /* Invoke the annotated export through the backend and assert the value. */
    std::uint32_t result = 0;
    const int called = browser_wasm_call_named_export(*instance, "mobagen_smoke_add", 20, 22, &result);
    check(called == 0, "mobagen_smoke_add invoked through the backend");
    check(called == 0 && result == 42, "mobagen_smoke_add(20, 22) returned 42");

    /* 1b. Todo 10: read the annotation table live and dispatch through the
       generic descriptor-driven marshaller. */
    std::vector<mobagen::modules::ModuleManifestExport> annotated;
    const auto memory = instance->memory();
    check(read_annotation_exports(memory.data(), memory.size(), annotated), "annotation table read from live guest memory");
    if (!annotated.empty()) {
      const auto* mul = static_cast<const mobagen::modules::ModuleManifestExport*>(nullptr);
      const auto* span_sum = static_cast<const mobagen::modules::ModuleManifestExport*>(nullptr);
      for (const auto& entry : annotated) {
        if (entry.name == "mobagen_smoke_mul") mul = &entry;
        if (entry.name == "mobagen_smoke_span_sum") span_sum = &entry;
      }
      check(mul != nullptr && mul->marshaling.has_value(), "mobagen_smoke_mul descriptor decoded from the annotation table");

      if (mul != nullptr && mul->marshaling.has_value()) {
        std::array<std::uint32_t, 2> result_cells{};
        const std::array arguments{std::uint32_t{6}, std::uint32_t{7}};
        const auto dispatched = browser_wasm_invoke_typed_export(*instance, mul->name, *mul->marshaling, arguments, result_cells);
        check(dispatched == 0, "mobagen_smoke_mul dispatched through the generic descriptor marshaller");
        check(dispatched == 0 && result_cells[0] == 42, "mobagen_smoke_mul(6, 7) returned 42 through the descriptor path");
      }

      if (span_sum != nullptr && span_sum->marshaling.has_value()) {
        /* A span cell names a guest-memory (offset,size) pair. Stage the pair
           at a real linear offset and five data bytes after it. */
        auto writable = instance->writable_memory();
        check(writable.size() >= 4096, "guest memory writable for span staging");
        if (writable.size() >= 4096) {
          const std::uint32_t pair_offset = 2048;
          const std::uint32_t data_offset = 2064;
          for (std::size_t index = 0; index < 4; ++index) {
            writable[pair_offset + index] = std::byte{0};
          }
          writable[pair_offset + 0] = std::byte{static_cast<std::uint8_t>(data_offset & 0xffU)};
          writable[pair_offset + 1] = std::byte{static_cast<std::uint8_t>((data_offset >> 8U) & 0xffU)};
          writable[pair_offset + 4] = std::byte{5};
          for (std::size_t index = 0; index < 5; ++index) writable[data_offset + index] = std::byte{2};
          std::array<std::uint32_t, 2> result_cells{};
          const std::array<std::uint32_t, 1> span_cells{pair_offset};
          const auto dispatched = browser_wasm_invoke_typed_export(*instance, span_sum->name, *span_sum->marshaling, span_cells, result_cells);
          check(dispatched == 0, "mobagen_smoke_span_sum dispatched through the descriptor marshaller");
          check(dispatched == 0 && result_cells[0] == 10, "mobagen_smoke_span_sum({2,2,2,2,2}) returned 10 through the descriptor path");
        }
      }

      /* Out-of-bounds span cells are rejected before any call. */
      if (span_sum != nullptr && span_sum->marshaling.has_value()) {
        std::array<std::uint32_t, 2> result_cells{};
        const std::array<std::uint32_t, 1> out_of_bounds{0xffff0000U};
        const auto rejected = browser_wasm_invoke_typed_export(*instance, span_sum->name, *span_sum->marshaling, out_of_bounds, result_cells);
        check(rejected == -3, "out-of-bounds span cells rejected before the call");
      }
    }

    auto activated = activate_portable_wasm_plugin(std::move(instance));
    check(activated.ok(), "guest activated (host imports bound, configure + start)");
    if (!activated.ok() && !activated.issues.empty()) {
      std::printf("[browser-smoke]   activation issue: %s\n", activated.issues.front().message.c_str());
    } else if (activated.ok() && activated.activation != nullptr) {
      auto quiesced = activated.activation->quiesce();
      auto stopped = quiesced.ok() ? activated.activation->stop() : quiesced;
      check(stopped.ok(), "guest quiesced + stopped cleanly");
    }
  }

  /* 2. Failure path: invalid wasm bytes must surface a load issue, not crash.
     Valid 8-byte header + garbage body trips the browser compile — the exact
     class of throw the backend must map to BackendFailure. */
  static const std::byte invalid_bytes[]{std::byte{0x00}, std::byte{0x61}, std::byte{0x73}, std::byte{0x6d},
                                         std::byte{0x01}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00},
                                         std::byte{0x55}, std::byte{0x99}};
  const std::filesystem::path invalid_path{"/mobagen-smoke/invalid.plugin.wasm"};
  check(stage_file(invalid_path, invalid_bytes), "invalid bytes staged onto MEMFS");

  auto invalid = load_portable_wasm_plugin_binary(invalid_path, backend);
  bool invalid_rejected = false;
  bool backend_failure = false;
  for (const auto& issue : invalid.issues) {
    invalid_rejected = true;
    if (issue.code == PortableWasmPluginLoadIssueCode::BackendFailure) {
      backend_failure = true;
      std::printf("[browser-smoke]   invalid-bytes issue: %s\n", issue.message.c_str());
    }
  }
  check(invalid_rejected && !invalid.ok(), "invalid wasm bytes yielded a load issue (no crash)");
  check(backend_failure, "invalid wasm bytes mapped to the BackendFailure issue code");

  if (failures == 0) std::printf("browser-backend-smoke-ok\n");
  return failures == 0 ? 0 : 1;
}
