/*
 * BrowserWasmBackend module-loading smoke (dynamic-loading-all-platforms todo 8).
 *
 * Emscripten-only executable, booted headlessly by scripts/smoke_web.mjs
 * (same --variant CLI as todo 5). Exercises the REAL loader path —
 * load_portable_wasm_plugin_binary -> BrowserWasmBackend::instantiate ->
 * query_portable_wasm_plugin (descriptor decode) -> activate (host imports
 * bound, configure, start) — then invokes the guest's annotated export
 * through the backend and asserts the returned value, plus the invalid-bytes
 * failure path (BackendFailure issue, no crash).
 *
 * The embedded guest bytes are staged onto the emscripten MEMFS so the
 * production file-based loader runs verbatim; no loader code changed.
 *
 * Web builds compile without exceptions and without a test framework
 * (BUILD_TESTING is OFF on emscripten), so failures print a FATAL marker and
 * return nonzero; the node runner treats a nonzero exit and the missing
 * success marker as a failed smoke.
 */
#include "browser_wasm_backend.hpp"

#include "plugins/wasm_runtime.hpp"

#include <mobagen/plugin/wasm_abi.h>

#include <cstdint>
#include <cstdio>
#include <filesystem>
#include <fstream>
#include <span>
#include <vector>

/* Generated by the guest-build step: mobagen_smoke_guest_wasm.h */
#include "mobagen_smoke_guest_wasm.h"

namespace {

  int failures = 0;

  void check(bool ok, const char* what) {
    if (ok) {
      std::printf("[browser-smoke] PASS: %s\n", what);
    } else {
      std::printf("[browser-smoke] FATAL: %s\n", what);
      ++failures;
    }
  }

  bool stage_file(const std::filesystem::path& path, std::span<const std::byte> bytes) {
    std::error_code error;
    std::filesystem::create_directories(path.parent_path(), error);
    std::ofstream out{path, std::ios::binary | std::ios::trunc};
    if (!out.is_open()) return false;
    out.write(reinterpret_cast<const char*>(bytes.data()), static_cast<std::streamsize>(bytes.size()));
    out.close();
    return out.good();
  }

}  // namespace

int main() {
  using namespace mobagen::plugins;

  BrowserWasmBackend backend;

  /* 1. Happy path: the production loader pipeline over the embedded guest. */
  const std::span<const std::byte> guest{reinterpret_cast<const std::byte*>(mobagen_smoke_guest_wasm),
                                         mobagen_smoke_guest_wasm_bytes};
  const std::filesystem::path guest_path{"/mobagen-smoke/reference.plugin.wasm"};
  check(stage_file(guest_path, guest), "reference guest staged onto MEMFS");

  auto loaded = load_portable_wasm_plugin_binary(guest_path, backend);
  check(loaded.ok(), "reference guest loaded through BrowserWasmBackend (sync instantiate + descriptor query)");
  if (!loaded.ok() && !loaded.issues.empty()) {
    std::printf("[browser-smoke]   load issue: %s\n", loaded.issues.front().message.c_str());
  }
  if (loaded.ok() && loaded.plugin.has_value()) {
    check(loaded.plugin->provider().id == "mobagen.browser-smoke.default", "queried provider id matches the guest descriptor");

    auto instance = loaded.plugin->take_instance();
    check(instance != nullptr, "loaded instance taken for direct export invocation");

    /* Invoke the annotated export through the backend and assert the value. */
    std::uint32_t result = 0;
    const int called = browser_wasm_call_named_export(*instance, "mobagen_smoke_add", 20, 22, &result);
    check(called == 0, "mobagen_smoke_add invoked through the backend");
    check(called == 0 && result == 42, "mobagen_smoke_add(20, 22) returned 42");

    auto activated = activate_portable_wasm_plugin(std::move(instance));
    check(activated.ok(), "guest activated (host imports bound, configure + start)");
    if (!activated.ok() && !activated.issues.empty()) {
      std::printf("[browser-smoke]   activation issue: %s\n", activated.issues.front().message.c_str());
    } else if (activated.ok() && activated.activation != nullptr) {
      auto quiesced = activated.activation->quiesce();
      auto stopped = quiesced.ok() ? activated.activation->stop() : quiesced;
      check(stopped.ok(), "guest quiesced + stopped cleanly");
    }
  }

  /* 2. Failure path: invalid wasm bytes must surface a load issue, not crash.
     Valid 8-byte header + garbage body trips the browser compile — the exact
     class of throw the backend must map to BackendFailure. */
  static const std::byte invalid_bytes[]{std::byte{0x00}, std::byte{0x61}, std::byte{0x73}, std::byte{0x6d},
                                         std::byte{0x01}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00},
                                         std::byte{0x55}, std::byte{0x99}};
  const std::filesystem::path invalid_path{"/mobagen-smoke/invalid.plugin.wasm"};
  check(stage_file(invalid_path, invalid_bytes), "invalid bytes staged onto MEMFS");

  auto invalid = load_portable_wasm_plugin_binary(invalid_path, backend);
  bool invalid_rejected = false;
  bool backend_failure = false;
  for (const auto& issue : invalid.issues) {
    invalid_rejected = true;
    if (issue.code == PortableWasmPluginLoadIssueCode::BackendFailure) {
      backend_failure = true;
      std::printf("[browser-smoke]   invalid-bytes issue: %s\n", issue.message.c_str());
    }
  }
  check(invalid_rejected && !invalid.ok(), "invalid wasm bytes yielded a load issue (no crash)");
  check(backend_failure, "invalid wasm bytes mapped to the BackendFailure issue code");

  if (failures == 0) std::printf("browser-backend-smoke-ok\n");
  return failures == 0 ? 0 : 1;
}
